### ISSUE TITLE
UniversalPlugin and MessageAnalyzer

### ISSUE THREAD

**Issue by gw2-research** [fshauge/guild-wars-2-modding#1]
Hello, ussuing a issue in place of a pm

I recently found a thing called "UniversalPlugin" and a "MessageAnalyzer" for gw2 written in .net

in the metadata of those dlls there's the name "Markus Hauge", I was wondering if it was you, and if you would like to talk further about this privately to make this tool work again.

**Comment by fshauge** [comment]
Yes, that's me. Add me on Skype: iphantom.dev
